### PR TITLE
Update react examples

### PR DESCRIPTION
**Pull request by iamonuwa**

### CODE REVIEW

**Comment by chaitanyapotti** [comment]
I like this implementation but can we do this without assigning to window.torus?

**Comment by iamonuwa** [comment]
> I like this implementation but can we do this without assigning to window.torus?

This is a basic implementation, when implemented on production ready app, the state management tool could come in handy for this over the window. But am open to suggestions.

**Comment by chaitanyapotti** [comment]
I think this is fine.
Please update the examples with the new content in vue-app and we can merge this PR then

**Comment by chaitanyapotti** [comment]
Please clean up the UI.
Test all the buttons if they work (some don't)

**Comment by chaitanyapotti** [comment]
I updated the react basic example to make it work. Please do the same for angular and react-dynamic apps

**Pull request merged**
