### PR TITLE
**Do not merge** Add angular example

### PR DESCRIPTION
**Pull request by iamonuwa**

### CODE REVIEW

**Comment by rathishubham7** [comment]
Screenshot 2019-12-20 at 2 34 55 PM

Handle close window events.

**Comment by rathishubham7** [comment]
image
Issue with send eth.

**Comment by chaitanyapotti** [comment]
Please make this look and work exactly like the react-basic-app

**Comment by iamonuwa** [comment]
Okay

**Comment by iamonuwa** [comment]
Closing this in favor of #90

**Pull request closed without merging**
